name: Umbraco Cloud Sync

on:
  workflow_call:
    secrets:
      projectId: 
        required: true
      umbracoCloudApiKey:
        required: true
  
env:
  projectId: ${{ secrets.projectId }}
  umbracoCloudApiKey: ${{ secrets.umbracoCloudApiKey }}

jobs:
  preflight:
    name: Preflight checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest Deployment
        id: latest-deployment
        run: |
          bash ${{GITHUB_WORKSPACE}}/.github/scripts/get_latest_deployment.sh \
          ${{ env.projectId }} \
          ${{ env.umbracoCloudApiKey }} \
          GITHUB
        shell: bash
         
    outputs: 
      latestDeploymentId: ${{ steps.latest-deployment.outputs.latestDeploymentId }}

  checkForChanges:
    name: Check if there are changes since latest deployment
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Changes From Cloud
        id: latest-changes
        env:
          latestDeploymentId: ${{ needs.preflight.outputs.latestDeploymentId }}
        if: ${{ env.latestDeploymentId != '' }}
        run: |
          bash ${{GITHUB.WORKSPACE}}/.github/scripts/get_changes_by_id.sh \
          ${{ env.projectId }} \
          ${{ env.umbracoCloudApiKey }} \
          ${{ env.latestDeploymentId }} \
          ${{GITHUB.WORKSPACE}}/patch \
          GITHUB
        shell: bash

      - name: See diff content if any
        if: ${{ steps.latest-changes.outputs.remoteChanges == 'yes' }}
        run: get-content ${{GITHUB.WORKSPACE}}/patch/git-patch.diff
        shell: pwsh

      - name: Store diff before applying
        if: ${{ steps.latest-changes.outputs.remoteChanges == 'yes' }}
        uses: actions/upload-artifact@v3
        with:
          name: git-patch
          path: ${{GITHUB.WORKSPACE}}/patch/git-patch.diff
          retention-days: 1

    outputs:
      remoteChanges: ${{ steps.latest-changes.outputs.remoteChanges }}  

  applyRemoteChanges:
    name: Apply remote changes
    needs: [preflight, checkForChanges]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ needs.checkForChanges.outputs.remoteChanges == 'yes' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get stored diff
        if: ${{ needs.checkForChanges.outputs.remoteChanges == 'yes' }}
        uses: actions/download-artifact@v3
        with:
          name: git-patch
          path: ${{GITHUB.WORKSPACE}}/patch

      - name: Applying git patch to branch
        if: ${{ needs.checkForChanges.outputs.remoteChanges == 'yes' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git apply ${{GITHUB.WORKSPACE}}/patch/git-patch.diff
          git add *
          git commit -m "Adding cloud changes since deployment ${{ needs.preflight.outputs.latestDeploymentId }} [skip ci]"
          git push